baseurl = "/"
languageCode = "en-us"
title = "Tasty Licks"

[params]
  description = "What your restaurant menu could look like"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
   name = "Food"
   url  = "/food"
   weight = 2